micronaut:
  application:
    name: personas
  server:
    cors:
      enabled: true
    netty:
      access-logger:
        enabled: true
        logger-name: personas
        log-format: common
    port: 8081
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:mysql://127.0.0.1:3310/personas
    username: root
    password: root
    max-lifetime: 480000
    minimum-idle: 5
    maximum-pool-size: 50
    idle-timeout: 160000
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
#jpa.default.properties.hibernate.hbm2ddl.auto: update
